feat: add basic README
morpho-org/morpho-seatbelt pull request #22
Opened 2023-05-30 04:53 UTC by pakim249CAL

2023-05-30 07:08 UTC, MerlinEgalite approved these changes

2023-05-30 07:08 UTC, MerlinEgalite commented on README.md
> +Morpho Seatbelt provides a framework for testing governance transactions to update Morpho Compound, Morpho AAVE V2, or Morpho AAVE V3. Morpho utilizes the [Zodiac](https://github.com/gnosis/zodiac) c
```suggestion
Morpho Seatbelt provides a framework for testing governance transactions to update Morpho Optimizers. Morpho utilizes the [Zodiac](https://github.com/gnosis/zodiac) collection of tools to enforce transaction delays and restrict certain functions to addresses with an appropriate role. Some key utilities included are reading gnosis safe transactions from a json, reading key internal state variables of contracts without external getters, and minimal interfaces to limit dependencies. 

```

2023-05-30 07:08 UTC, MerlinEgalite commented on README.md
> +For any question or feedback you can send an email to [merlin@morpho.xyz](mailto:merlin@morpho.xyz).
maybe we should redirect the discord instead

2023-05-30 07:27 UTC, Tristan22400 approved these changes

2023-05-30 09:04 UTC, Rubilmax approved these changes

2023-05-30 11:09 UTC, makcandrov submitted a review, later dismissed

2023-05-30 13:45 UTC, MerlinEgalite approved these changes

2023-05-30 15:34 UTC, MerlinEgalite submitted a review, later dismissed

2023-05-30 15:46 UTC, Rubilmax requested changes

2023-05-30 15:46 UTC, Rubilmax commented on README.md
> +For any question or feedback you can join the Morpho [discord](https://discord.gg/BWXbJMHMdz).
Prefer using `discord.morpho.xyz` to avoid having discord invitation takeover issues or just be easier to maintain if we change the invitation link

2023-05-30 17:53 UTC, MerlinEgalite approved these changes

2023-05-31 07:32 UTC, Rubilmax approved these changes

2023-05-31 07:48 UTC, merged